#!/bin/bash
# inf_process

#awk '/^Pid/ { printf $1}' /proc/$1/status 
#echo -en "\t"
#awk '/PPid/ { printf $1}' /proc/$1/status
#echo -en "\t"
#awk '/State/ { printf $1}' /proc/$1/status
#echo -en "\t"
#awk '/Name/ { print $1}' /proc/$1/status

echo -en "PID\tPPID\tSTATE\tNAME\n"

awk '/^Pid/ { printf  $2}' /proc/$1/status
echo -en "\t"
awk '/PPid/ { printf  $2}' /proc/$1/status
echo -en "\t"
awk '/State/ { printf  $2}' /proc/$1/status
echo -en "\t"
awk '/Name/ { print  $2}' /proc/$1/status
